global using System.Diagnostics.CodeAnalysis;
global using System.Text.Json;
global using Amazon.DynamoDBv2;
global using Amazon.DynamoDBv2.DataModel;
global using Carter;
global using FluentValidation;
global using MediatR;
global using Microsoft.AspNetCore.Mvc;
global using Serilog;
