name: ASP.NET 8 Build

on:
  push:
    branches:
      - 'feature**'
  # pull_request:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.x' # Change to the version of .NET Core you need
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release

  Unit-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.x' # Change to the version of .NET Core you need
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Test
      run: dotnet test

  create_pull_request:
    runs-on: ubuntu-latest
    needs: build
    env:
      GH_TOKEN: ${{ secrets.GH_PAT }}  # Use the personal access token stored as a secret
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install GitHub CLI
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: |
        npm install -g github-cli

    # - name: Read Pull Request Template
    #   id: read_template
    #   run: |
    #     cat ../pull_request_template.md

    - name: Create Pull Request
      run: |
        gh pr create --base develop --head main --title "Merge changes from main to develop" --body "$(echo '${{ steps.read_template.outputs.stdout }}')" --token $GH_TOKEN